!yamlscript/v0/
::
  use: helpers

apiVersion: v1
kind: ServiceAccount
metadata:
  name:: serviceAccountName()
  labels:: common-labels()
  ::
    when Values.serviceAccount.annotations.?::
      annotations:: Values.serviceAccount.annotations
automountServiceAccountToken::
  Values.serviceAccount.automount
